In [11]:
import numpy as np

y = np.load("data/I5eee5cfbea3b44d4965b0930cf91bf1d.npy")
X = np.load("data/X5eee5cfbea3b44d4965b0930cf91bf1d.npy")

In [12]:
X.shape

(9500, 42)

In [13]:
y_n = y.argmax(axis=1)

In [14]:
y_n

array([2, 5, 6, ..., 6, 5, 6])

In [15]:
y.shape

(9500, 7)

In [29]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes = (28,),activation = 'logistic', max_iter=50,verbose=True).fit(X, y_n)


Iteration 1, loss = 1.21390268
Iteration 2, loss = 1.01418937
Iteration 3, loss = 0.92283593
Iteration 4, loss = 0.84109108
Iteration 5, loss = 0.76218945
Iteration 6, loss = 0.69479118
Iteration 7, loss = 0.62387663
Iteration 8, loss = 0.56553596
Iteration 9, loss = 0.51072052
Iteration 10, loss = 0.46662405
Iteration 11, loss = 0.42567306
Iteration 12, loss = 0.39192898
Iteration 13, loss = 0.36449636
Iteration 14, loss = 0.33754998
Iteration 15, loss = 0.31400522
Iteration 16, loss = 0.29933487
Iteration 17, loss = 0.28180564
Iteration 18, loss = 0.26839562
Iteration 19, loss = 0.25280358
Iteration 20, loss = 0.24181440
Iteration 21, loss = 0.23232846
Iteration 22, loss = 0.22046664
Iteration 23, loss = 0.21137903
Iteration 24, loss = 0.20071605
Iteration 25, loss = 0.19547654
Iteration 26, loss = 0.18594652
Iteration 27, loss = 0.19049547
Iteration 28, loss = 0.18068068
Iteration 29, loss = 0.16978664
Iteration 30, loss = 0.16315131
Iteration 31, loss = 0.16058367
Iteration 32, los

/home/keen/.pyenv/versions/3.8.16/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [30]:
clf.predict_proba(X)[2]

array([6.07825313e-04, 1.91097630e-03, 1.02457594e-02, 9.87235439e-01])

In [31]:
clf.predict(X)[1]

5

In [32]:
y[2]

array([0., 0., 0., 0., 0., 0., 1.])